node_lines:
- node_line_name: retrieve_node_line  # Arbitrary node line name
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision, retrieval_map]
      top_k: 10
      modules:
        - module_type: vectordb             # 우리는 Hybrid를 사용할 수 없기 때문에 vectordb만 사용
          embedding_model: [huggingface_baai_bge_small, ko-sroberta-multitask, ko-sbert-nli, kosimcse]
- node_line_name: post_retrieve_node_line  # Arbitrary node line name
  nodes:
    - node_type: prompt_maker
      strategy:
        metrics: [bleu, meteor, rouge, sem_score]   # bert_score
      modules:
        - module_type: fstring
          prompt: "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
    - node_type: generator
      strategy:
        metrics: [bleu, meteor, rouge, sem_score]   # bert_score, g_eval  : 아주 좋은 평가지표지만 오래걸림 
      modules:
        - module_type: llama_index_llm
          llm: openai
          model: [gpt-3.5-turbo-16k, gpt-3.5-turbo]
          batch: 2